-- AGEL Commissioning Tracker Database Export
-- Generated: 2026-01-09T05:40:43.936Z

-- Commissioning Projects
CREATE TABLE IF NOT EXISTS commissioning_projects (
  id SERIAL PRIMARY KEY,
  fiscal_year VARCHAR(20),
  sno INTEGER,
  project_name VARCHAR(255),
  spv VARCHAR(255),
  project_type VARCHAR(100),
  plot_location VARCHAR(255),
  capacity FLOAT,
  plan_actual VARCHAR(50),
  apr FLOAT, may FLOAT, jun FLOAT,
  jul FLOAT, aug FLOAT, sep FLOAT,
  oct FLOAT, nov FLOAT, dec FLOAT,
  jan FLOAT, feb FLOAT, mar FLOAT,
  total_capacity FLOAT,
  cumm_till_oct FLOAT,
  q1 FLOAT, q2 FLOAT, q3 FLOAT, q4 FLOAT,
  category VARCHAR(255),
  section VARCHAR(10),
  included_in_total BOOLEAN DEFAULT TRUE,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

DELETE FROM commissioning_projects;

INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'AGEL Merchant', 'ARE56L', 'Merchant', 'S-08', 250, 'Plan', 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 250, 250, 250, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'AGEL Merchant', 'ARE56L', 'Merchant', 'S-08', 250, 'Rephase', 75, 50, 50, 75, 0, 0, 0, 0, 0, 0, 0, 0, 250, 250, 125, 125, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'AGEL Merchant', 'ARE56L', 'Merchant', 'S-08', 250, 'Actual', 75, 50, 0, 125, 0, 0, 0, 0, 0, 0, 0, 0, 250, 250, 125, 125, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'MLP AP New', 'ARE57L', 'PPA', 'A-11', 187.5, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 187.5, 187.5, 187.5, 187.5, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'MLP AP New', 'ARE57L', 'PPA', 'A-11', 0, 'Rephase', 112.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 187.5, 187.5, 187.5, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'MLP AP New', 'ARE57L', 'PPA', 'A-11', 0, 'Actual', 112.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 187.5, 187.5, 187.5, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 5, 'SECI H-3', 'AHEJ5L', 'PPA', 'A-13', 570, 'Plan', 0, 275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 295, 570, 570, 570, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 5, 'SECI H-3', 'AHEJ5L', 'PPA', 'A-13', 0, 'Rephase', 0, 150, 75, 0, 50, 50, 100, 0, 0, 0, 0, 145, 570, 570, 295, 125, 150, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 5, 'SECI H-3', 'AHEJ5L', 'PPA', 'A-13', 0, 'Actual', 0, 150, 0, 50, 75, 75, 0, 75, 0, 0, 0, 145, 570, 495, 295, 125, 150, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 6, 'AGEL Merchant', 'ARE45L', 'Merchant', 'A-14', 250, 'Plan', 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 250, 250, 250, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 6, 'AGEL Merchant', 'ARE45L', 'Merchant', 'A-14', 0, 'Rephase', 0, 125, 0, 75, 0, 0, 0, 0, 0, 0, 0, 50, 250, 250, 175, 75, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 6, 'AGEL Merchant', 'ARE45L', 'Merchant', 'A-14', 0, 'Actual', 0, 125, 0, 0, 75, 0, 0, 0, 0, 0, 0, 50, 250, 250, 175, 75, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 7, 'MLP T3 AP', 'ARE56L', 'PPA', 'S-06', 500, 'Plan', 0, 100, 300, 0, 0, 0, 0, 0, 0, 0, 0, 100, 500, 500, 200, 300, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 7, 'MLP T3 AP', 'ARE56L', 'PPA', 'S-06', 0, 'Rephase', 0, 137.5, 112.5, 0, 50, 50, 50, 0, 0, 0, 0, 100, 500, 500, 237.5, 162.5, 100, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 7, 'MLP T3 AP', 'ARE56L', 'PPA', 'S-06', 0, 'Actual', 0, 137.5, 0, 87.5, 100, 0, 75, 0, 0, 0, 0, 100, 500, 500, 237.5, 187.5, 75, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 8, 'Google Hybrid', 'ARE3L', 'Merchant', 'A-6', 25, 'Plan', 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 25, 25, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 8, 'Google Hybrid', 'ARE3L', 'Merchant', 'A-6', 0, 'Rephase', 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 25, 0, 25, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 8, 'Google Hybrid', 'ARE3L', 'Merchant', 'A-6', 0, 'Actual', 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 25, 0, 25, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 9, 'AGEL Merchant', 'ASEJ6PL', 'Merchant', 'A-6', 35, 'Plan', 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 35, 35, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 9, 'AGEL Merchant', 'ASEJ6PL', 'Merchant', 'A-6', 0, 'Rephase', 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 35, 0, 35, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 9, 'AGEL Merchant', 'ASEJ6PL', 'Merchant', 'A-6', 0, 'Actual', 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 35, 0, 35, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 10, 'AGEL Hybrid Merchant', 'AGE25BL', 'Merchant', 'S-8', 100, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 100, 0, 0, 0, 0, 100, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 10, 'AGEL Hybrid Merchant', 'AGE25BL', 'Merchant', 'S-8', 0, 'Rephase', 0, 0, 0, 50, 0, 0, 50, 0, 0, 0, 0, 0, 100, 100, 0, 50, 50, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 10, 'AGEL Hybrid Merchant', 'AGE25BL', 'Merchant', 'S-8', 0, 'Actual', 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 100, 100, 0, 100, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AHEJ5L', 'Merchant', 'A-15a', 150, 'Plan', 0, 0, 0, 0, 0, 0, 50, 0, 100, 0, 0, 0, 150, 50, 0, 0, 50, 100, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AHEJ5L', 'Merchant', 'A-15a', 0, 'Rephase', 0, 0, 0, 0, 0, 50, 50, 0, 50, 0, 0, 0, 150, 100, 0, 0, 100, 50, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AHEJ5L', 'Merchant', 'A-15a', 0, 'Actual', 0, 0, 0, 0, 50, 0, 0, 0, 50, 50, 0, 0, 150, 50, 0, 50, 0, 100, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Hybrid Merchant', 'AGE26BL', 'Merchant', 'S-5', 292, 'Plan', 100, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 292, 292, 292, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Hybrid Merchant', 'AGE26BL', 'Merchant', 'S-5', 0, 'Rephase', 0, 0, 50, 0, 75, 62, 105, 0, 0, 0, 0, 0, 292, 292, 0, 125, 167, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Hybrid Merchant', 'AGE26BL', 'Merchant', 'S-5', 0, 'Actual', 0, 0, 0, 0, 50, 0, 50, 50, 75, 67, 0, 0, 292, 100, 0, 50, 100, 142, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 13, 'AGEL Merchant', 'AGE24L', 'Merchant', 'S-5', 150, 'Plan', 50, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 150, 150, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 13, 'AGEL Merchant', 'AGE24L', 'Merchant', 'S-5', 0, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 50, 100, 0, 0, 150, 0, 0, 0, 0, 150, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 13, 'AGEL Merchant', 'AGE24L', 'Merchant', 'S-5', 0, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 62.5, 87.5, 0, 0, 150, 0, 0, 0, 0, 150, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 15, 'Cement - Hybrid', 'ACL', 'Group', 'A-1', 125, 'Plan', 0, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 125, 125, 125, 0, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 15, 'Cement - Hybrid', 'ACL', 'Group', 'A-1', 0, 'Rephase', 0, 0, 0, 75, 0, 50, 0, 0, 0, 0, 0, 0, 125, 125, 0, 75, 50, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 15, 'Cement - Hybrid', 'ACL', 'Group', 'A-1', 0, 'Actual', 0, 0, 0, 0, 50, 0, 0, 75, 0, 0, 0, 0, 125, 50, 0, 50, 75, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 16, 'MLP T3 AP', 'AGE25CL', 'PPA', 'A-6', 75, 'Plan', 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 0, 0, 75, 75, 0, 0, 75, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 16, 'MLP T3 AP', 'AGE25CL', 'PPA', 'A-6', 0, 'Rephase', 0, 0, 0, 75, 0, 0, 0, 0, 0, 0, 0, 0, 75, 75, 0, 75, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 16, 'MLP T3 AP', 'AGE25CL', 'PPA', 'A-6', 0, 'Actual', 0, 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 0, 75, 0, 0, 0, 75, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 17, 'MLP T1 J&K', 'AGE26AL', 'PPA', 'A-16', 50, 'Plan', 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 50, 50, 0, 50, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 17, 'MLP T1 J&K', 'AGE26AL', 'PPA', 'A-16', 0, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 50, 0, 0, 0, 50, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 17, 'MLP T1 J&K', 'AGE26AL', 'PPA', 'A-16', 0, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 50, 0, 0, 0, 0, 50, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 18, 'MLP T1 CG', 'AGE26AL', 'PPA', 'A-16', 200, 'Plan', 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 200, 200, 0, 0, 200, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 18, 'MLP T1 CG', 'AGE26AL', 'PPA', 'A-16', 0, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 50, 100, 50, 0, 0, 200, 0, 0, 0, 50, 150, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 18, 'MLP T1 CG', 'AGE26AL', 'PPA', 'A-16', 0, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 175, 25, 0, 0, 200, 0, 0, 0, 0, 200, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 19, 'MLP T1 TN', 'AGE26AL', 'PPA', 'A-16', 167, 'Plan', 0, 0, 0, 0, 0, 167, 0, 0, 0, 0, 0, 0, 167, 167, 0, 0, 167, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 19, 'MLP T1 TN', 'AGE26AL', 'PPA', 'A-16', 0, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 50, 117, 0, 0, 0, 167, 0, 0, 0, 50, 117, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 19, 'MLP T1 TN', 'AGE26AL', 'PPA', 'A-16', 0, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 100, 67, 0, 0, 167, 0, 0, 0, 0, 167, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 20, 'MLP T1 OR', 'AGE26AL', 'PPA', 'A-16', 333, 'Plan', 0, 0, 0, 0, 333, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 333, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 20, 'MLP T1 OR', 'AGE26AL', 'PPA', 'A-16', 0, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 100, 100, 133, 0, 333, 0, 0, 0, 0, 333, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 20, 'MLP T1 OR', 'AGE26AL', 'PPA', 'A-16', 0, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 150, 183, 0, 0, 333, 0, 0, 0, 0, 333, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 21, 'MLP T1 TR', 'AGE26AL', 'PPA', 'A10a', 50, 'Plan', 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 50, 50, 0, 50, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 21, 'MLP T1 TR', 'AGE26AL', 'PPA', 'A10a', 0, 'Rephase', 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 50, 50, 0, 50, 0, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 21, 'MLP T1 TR', 'AGE26AL', 'PPA', 'A10a', 0, 'Actual', 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 50, 50, 0, 0, 50, 0, 'Khavda Solar', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Cement  RJ', 'ACL', 'Group', 'Essel park', 300, 'Plan', 0, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 300, 300, 0, 0, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Cement  RJ', 'ACL', 'Group', 'Essel park', 300, 'Rephase', 0, 0, 150, 150, 0, 0, 0, 0, 0, 0, 0, 0, 300, 300, 0, 300, 0, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Cement  RJ', 'ACL', 'Group', 'Essel park', 300, 'Actual', 0, 0, 0, 150, 0, 0, 0, 150, 0, 0, 0, 0, 300, 150, 0, 150, 150, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 2, 'Merchant', 'ASEJ6PL', 'Merchant', 'Bap', 50, 'Plan', 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 50, 50, 0, 0, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 2, 'Merchant', 'ASEJ6PL', 'Merchant', 'Bap', 50, 'Rephase', 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 50, 50, 0, 0, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 2, 'Merchant', 'ASEJ6PL', 'Merchant', 'Bap', 50, 'Actual', 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 50, 50, 0, 0, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'MLP AP New', 'AGE26BL', 'PPA', 'Bandha', 534, 'Plan', 0, 0, 0, 0, 0, 0, 250, 284, 0, 0, 0, 0, 534, 250, 0, 0, 534, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'MLP AP New', 'AGE26BL', 'PPA', 'Bandha', 534, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 534, 0, 0, 0, 0, 534, 0, 0, 0, 534, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'MLP AP New', 'AGE26BL', 'PPA', 'Bandha', 534, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 4, 'MLP T1', 'AGE25BL', 'PPA', 'Bandha', 500, 'Plan', 0, 0, 0, 0, 0, 0, 0, 200, 300, 0, 0, 0, 500, 0, 0, 0, 200, 300, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 4, 'MLP T1', 'AGE25BL', 'PPA', 'Bandha', 500, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 250, 250, 0, 0, 500, 0, 0, 0, 0, 500, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 4, 'MLP T1', 'AGE25BL', 'PPA', 'Bandha', 500, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 250, 0, 250, 0, 0, 0, 0, 250, 'Rajasthan Solar', 'B', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'NHPC BOO', 'ASEB1PL', 'PPA', 'Baiya', 600, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Rajasthan Solar Additional 500MW', 'C', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'NHPC BOO', 'ASEB1PL', 'PPA', 'Baiya', 600, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Rajasthan Solar Additional 500MW', 'C', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'NHPC BOO', 'ASEB1PL', 'PPA', 'Baiya', 600, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 0, 300, 0, 0, 0, 0, 300, 'Rajasthan Solar Additional 500MW', 'C', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 25, 'KCTL', 'KCTL', 'Group', 'A-15a', 12.5, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 25, 'KCTL', 'KCTL', 'Group', 'A-15a', 12.5, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 12.5, 0, 0, 0, 0, 12.5, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 25, 'KCTL', 'KCTL', 'Group', 'A-15a', 12.5, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 12.5, 0, 0, 0, 0, 12.5, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 26, 'MCIPL', 'MCIPL', 'Group', 'A-15a', 12.5, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 26, 'MCIPL', 'MCIPL', 'Group', 'A-15a', 12.5, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 12.5, 0, 0, 0, 0, 12.5, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 26, 'MCIPL', 'MCIPL', 'Group', 'A-15a', 12.5, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 12.5, 0, 0, 0, 0, 12.5, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 27, 'AGEL Merchant', 'ASEJo6PL', 'Merchant', 'A-15a', 25, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 27, 'AGEL Merchant', 'ASEJo6PL', 'Merchant', 'A-15a', 25, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 25, 0, 0, 0, 0, 25, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 27, 'AGEL Merchant', 'ASEJo6PL', 'Merchant', 'A-15a', 25, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 25, 0, 0, 0, 0, 25, 'Khavda Solar Copper+Merchant 50MW', 'D1', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 23, 'AGEL Hybrid Merchant', 'AHEJ5L', 'Merchant', 'S-4', 300, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 150, 200, 0, 0, 350, 0, 0, 0, 0, 350, 'Khavda Solar Internal 650MW', 'D2', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 23, 'AGEL Hybrid Merchant', 'AHEJ5L', 'Merchant', 'S-4', 300, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 100, 100, 100, 0, 0, 300, 0, 0, 0, 100, 200, 'Khavda Solar Internal 650MW', 'D2', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 23, 'AGEL Hybrid Merchant', 'AHEJ5L', 'Merchant', 'S-4', 300, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Khavda Solar Internal 650MW', 'D2', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 24, 'MLP AP New', 'ARE57L', 'PPA', 'A-12', 350, 'Plan', 0, 0, 0, 0, 0, 0, 0, 100, 100, 100, 0, 0, 300, 0, 0, 0, 100, 200, 'Khavda Solar Internal 650MW', 'D2', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 24, 'MLP AP New', 'ARE57L', 'PPA', 'A-12', 350, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 150, 200, 0, 0, 0, 350, 0, 0, 0, 150, 200, 'Khavda Solar Internal 650MW', 'D2', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 24, 'MLP AP New', 'ARE57L', 'PPA', 'A-12', 350, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Khavda Solar Internal 650MW', 'D2', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'AGEL Merchant', 'AGE24L', 'Merchant', 'PSS-04', 52, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 52, 52, 52, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'AGEL Merchant', 'AGE24L', 'Merchant', 'PSS-04', 52, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 52, 52, 52, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'AGEL Merchant', 'AGE24L', 'Merchant', 'PSS-04', 52, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 52, 52, 52, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 2, 'Hybrid Cement', 'ACL', 'Group', 'PSS-04', 57.2, 'Plan', 31.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 57.2, 57.2, 57.2, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 2, 'Hybrid Cement', 'ACL', 'Group', 'PSS-04', 57.2, 'Rephase', 26, 31.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57.2, 57.2, 57.2, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 2, 'Hybrid Cement', 'ACL', 'Group', 'PSS-04', 57.2, 'Actual', 26, 31.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57.2, 57.2, 57.2, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'AGEL Merchant', 'AHEJ5L', 'Merchant', 'PSS-04', 62.40000000000001, 'Plan', 10.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 62.4, 62.4, 62.4, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'AGEL Merchant', 'AHEJ5L', 'Merchant', 'PSS-04', 62.40000000000001, 'Rephase', 0, 10.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 62.4, 62.4, 62.4, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 3, 'AGEL Merchant', 'AHEJ5L', 'Merchant', 'PSS-04', 62.40000000000001, 'Actual', 0, 10.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 62.4, 62.4, 62.4, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 4, 'AGEL Hybrid Merchant', 'AGE26BL', 'Merchant', 'PSS-10', 156, 'Plan', 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 156, 156, 156, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 4, 'AGEL Hybrid Merchant', 'AGE26BL', 'Merchant', 'PSS-10', 156, 'Rephase', 0, 119.6, 26, 10.4, 0, 0, 0, 0, 0, 0, 0, 0, 156, 156, 119.6, 36.4, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 4, 'AGEL Hybrid Merchant', 'AGE26BL', 'Merchant', 'PSS-10', 156, 'Actual', 0, 119.6, 26, 0, 0, 0, 0, 0, 0, 10.4, 0, 0, 156, 145.6, 119.6, 26, 0, 10.4, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 6, 'AGEL Merchant', 'ARE41L', 'Merchant', 'PSS-08', 130, 'Plan', 36.4, 93.60000000000001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 130, 130, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 6, 'AGEL Merchant', 'ARE41L', 'Merchant', 'PSS-08', 130, 'Rephase', 0, 0, 52, 26, 26, 26, 0, 0, 0, 0, 0, 0, 130, 130, 0, 104, 26, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 6, 'AGEL Merchant', 'ARE41L', 'Merchant', 'PSS-08', 130, 'Actual', 0, 0, 0, 124.8, 0, 0, 5.2, 0, 0, 0, 0, 0, 130, 130, 0, 124.8, 5.2, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 8, 'Google Hybrid', 'ARE3L', 'Merchant', 'PSS-08', 26, 'Plan', 0, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 26, 26, 0, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 7, 'Google Hybrid', 'ARE3L', 'Merchant', 'PSS-08', 15.6, 'Rephase', 0, 0, 0, 15.6, 0, 0, 0, 0, 0, 0, 0, 0, 15.6, 15.6, 0, 15.6, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 7, 'Google Hybrid', 'ARE3L', 'Merchant', 'PSS-08', 15.6, 'Actual', 0, 0, 15.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.6, 15.6, 0, 15.6, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 9, 'AGEL Hybrid Merchant', 'ASEJ6PL', 'Merchant', 'PSS-08', 62.40000000000001, 'Plan', 0, 41.6, 20.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62.40000000000001, 62.40000000000001, 41.6, 20.8, 0, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 9, 'AGEL Hybrid Merchant', 'ASEJ6PL', 'Merchant', 'PSS-08', 62.40000000000001, 'Rephase', 0, 0, 0, 0, 0, 62.40000000000001, 0, 0, 0, 0, 0, 0, 62.40000000000001, 62.40000000000001, 0, 0, 62.40000000000001, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 9, 'AGEL Hybrid Merchant', 'ASEJ6PL', 'Merchant', 'PSS-08', 62.40000000000001, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 31.2, 20.8, 10.4, 0, 62.4, 0, 0, 0, 0, 62.4, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 10, 'SECI H-3', 'AHEJ5L', 'PPA', 'PSS-05', 202.8, 'Plan', 0, 0, 72.8, 26, 26, 52, 26, 0, 0, 0, 0, 0, 202.8, 202.8, 0, 124.8, 78, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 10, 'SECI H-3', 'AHEJ5L', 'PPA', 'PSS-05', 202.8, 'Rephase', 0, 0, 0, 0, 0, 0, 104, 98.8, 0, 0, 0, 0, 202.8, 104, 0, 0, 202.8, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 10, 'SECI H-3', 'AHEJ5L', 'PPA', 'PSS-05', 202.8, 'Actual', 0, 0, 0, 0, 0, 78, 46.8, 57.2, 0, 0, 20.8, 0, 202.8, 124.8, 0, 0, 182, 20.8, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AGE25CL', 'Merchant', 'PSS-11', 156, 'Plan', 0, 0, 0, 0, 0, 0, 104, 52, 0, 0, 0, 0, 156, 104, 0, 0, 156, 0, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AGE25CL', 'Merchant', 'PSS-11', 156, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 104, 52, 0, 0, 156, 0, 0, 0, 0, 156, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AGE25CL', 'Merchant', 'PSS-11', 156, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 78, 62.40000000000001, 15.6, 0, 156, 0, 0, 0, 0, 156, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Merchant', 'AGE26AL', 'Merchant', 'PSS-12', 140.4, 'Plan', 0, 0, 0, 0, 0, 0, 0, 78, 62.40000000000001, 0, 0, 0, 140.4, 0, 0, 0, 78, 62.40000000000001, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Merchant', 'AGE26AL', 'Merchant', 'PSS-12', 140.4, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 78, 62.40000000000001, 0, 140.4, 0, 0, 0, 0, 140.4, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Merchant', 'AGE26AL', 'Merchant', 'PSS-12', 140.4, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 78, 62.40000000000001, 0, 140.4, 0, 0, 0, 0, 140.4, 'Khavda Wind', 'A', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AGE25CL', 'Merchant', 'PSS-11(32.2 MW)
PSS-14(67.6 MW)', 98.8, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 98.80000000000001, 0, 0, 0, 98.80000000000001, 0, 0, 0, 0, 98.80000000000001, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AGE25CL', 'Merchant', 'PSS-11(32.2 MW)
PSS-14(67.6 MW)', 98.8, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 98.80000000000001, 0, 0, 0, 98.80000000000001, 0, 0, 0, 0, 98.80000000000001, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 11, 'AGEL Merchant', 'AGE25CL', 'Merchant', 'PSS-11(32.2 MW)
PSS-14(67.6 MW)', 98.8, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 10.4, 15.6, 72.80000000000001, 0, 98.80000000000001, 0, 0, 0, 0, 98.80000000000001, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Merchant', 'AGE26AL', 'Merchant', 'PSS-14', 312, 'Plan', 0, 0, 0, 0, 0, 0, 0, 0, 41.6, 156, 114.4, 0, 312, 0, 0, 0, 0, 312, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Merchant', 'AGE26AL', 'Merchant', 'PSS-14', 312, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 41.6, 156, 114.4, 0, 312, 0, 0, 0, 0, 312, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 12, 'AGEL Merchant', 'AGE26AL', 'Merchant', 'PSS-14', 312, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 36.4, 135.2, 140.4, 0, 312, 0, 0, 0, 0, 312, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 13, 'AGEL Merchant', 'AGE25BL', 'Merchant', 'PSS-09', 10.4, 'Plan', 0, 0, 0, 0, 0, 0, 0, 10.4, 0, 0, 0, 0, 10.4, 0, 0, 0, 10.4, 0, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 13, 'AGEL Merchant', 'AGE25BL', 'Merchant', 'PSS-09', 10.4, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 10.4, 0, 0, 0, 0, 10.4, 0, 0, 0, 10.4, 0, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 13, 'AGEL Merchant', 'AGE25BL', 'Merchant', 'PSS-09', 10.4, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 10.4, 0, 0, 0, 10.4, 0, 0, 0, 0, 10.4, 'Khavda Wind Internal 421MW', 'B', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Merchant-Wind', 'AWEK3L', 'Merchant', 'Mundra North', 75.89999999999999, 'Plan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 75.89999999999999, NULL, 75.89999999999999, 0, 0, 0, 0, 75.89999999999999, 'Mundra Wind 76MW', 'C', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Merchant-Wind', 'AWEK3L', 'Merchant', 'Mundra North', 75.89999999999999, 'Rephase', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75.89999999999999, 0, 75.89999999999999, 0, 0, 0, 0, 75.89999999999999, 'Mundra Wind 76MW', 'C', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Merchant-Wind', 'AWEK3L', 'Merchant', 'Mundra North', 75.89999999999999, 'Actual', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75.89999999999999, 0, 75.89999999999999, 0, 0, 0, 0, 75.89999999999999, 'Mundra Wind 76MW', 'C', true, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Merchant-Wind', 'AWEK3L', 'Merchant', 'Mundra North', 247.5, 'Plan', 0, 350, 0, 0, 0, 0, 250, 484, 300, 0, 75.89999999999999, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Mundra Wind Internal 224.4MW', 'D', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Merchant-Wind', 'AWEK3L', 'Merchant', 'Mundra North', 247.5, 'Rephase', 313.5, 798.7, 425.5, 503, 353, 366.5, 458.5, 248.8, 721, 630, 320.4, 474, NULL, NULL, NULL, NULL, NULL, NULL, 'Mundra Wind Internal 224.4MW', 'D', false, false);
INSERT INTO commissioning_projects (fiscal_year, sno, project_name, spv, project_type, plot_location, capacity, plan_actual, apr, may, jun, jul, aug, sep, oct, nov, dec, jan, feb, mar, total_capacity, cumm_till_oct, q1, q2, q3, q4, category, section, included_in_total, is_deleted) VALUES ('FY_25-26', 1, 'Merchant-Wind', 'AWEK3L', 'Merchant', 'Mundra North', 247.5, 'Actual', 313.5, 798.7, 127.6, 387.3, 531.2, 203, 370, 818, 972, 388, 267, 474, NULL, NULL, NULL, NULL, NULL, NULL, 'Mundra Wind Internal 224.4MW', 'D', false, false);

-- Dropdown Options
CREATE TABLE IF NOT EXISTS dropdown_options (
  id SERIAL PRIMARY KEY,
  option_type VARCHAR(100),
  option_value VARCHAR(255),
  fiscal_year VARCHAR(20)
);

DELETE FROM dropdown_options;

INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('categories', 'Solar', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('categories', 'Wind', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('types', 'Merchant', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('types', 'PPA', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('types', 'Group', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ARE56L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ARE57L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AHEJ5L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ARE45L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ARE3L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ASEJ6PL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AGE25BL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AGE26BL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AGE24L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ACL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AGE25CL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AGE26AL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ASEB1PL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'KCTL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'MCIPL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ASEJo6PL', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'ARE41L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('spv', 'AWEK3L', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Khavda Solar', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Rajasthan Solar', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Rajasthan Solar Additional 500MW', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Khavda Solar Copper+Merchant 50MW', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Khavda Solar Internal 650MW', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Khavda Wind', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Khavda Wind Internal 421MW', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Mundra Wind 76MW', 'FY_25-26');
INSERT INTO dropdown_options (option_type, option_value, fiscal_year) VALUES ('sections', 'Mundra Wind Internal 224.4MW', 'FY_25-26');
